### PR TITLE
feat(sync): add auto sync fork action

### PR DESCRIPTION
**Pull request by lxb1226**
hi, this PR is to enable the auto-sync fork action.

### CODE REVIEW

**Comment by j178** [comment]
Sorry, could you clarify the purpose of this PR? I'm not sure this belongs in the repo.

**Comment by lxb1226** [comment]
Sometime, when we fork a repository, we want to automatically sync the fork to keep it up-to-date with the upstream repository. like this [sync-a-fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) , but it is automatically.

**Comment by j178** [comment]
Shouldn't this action be in the fork instead?

**Comment by lxb1226** [comment]
Yes, this action will be enable in the fork. However, we need to stay consistent with the upstream, so this YAML file needs to be in the upstream repository.

**Comment by j178** [comment]
Thanks, but I really don't think it's reasonable to put an action like this in the upstream repo just for some forks to auto sync. Not every fork wants to be auto synced I think, but this action cannot be opt-out.

**Comment by lxb1226** [comment]
This might be a bit misleading, as even in the fork, this action needs to be manually enabled, so it’s only useful for those who need it.

**Comment by j178** [comment]
Yeah, forks might enable action because they want to run the CI job, but this cron job auto runs every day unless them turn off the entire action.

I think a better solution is to place this commit at the top of your fork master branch. Let the sync action rebase during each sync so that this commit remains exclusive to the fork.

**Pull request closed without merging**
