### PR TITLE
refactor: revert #107 but using `enum_dispatch`

### PR DESCRIPTION
**Pull request by bxb100**
hi, @j178 , IMHO I think using [enum_dispatch](https://docs.rs/enum_dispatch/latest/enum_dispatch/) to remove boilerplate code much better, PTAL

### CODE REVIEW

**Comment by j178** [comment]
Thanks for letting me know about `enum_dispatch`. Before #107 (and in this PR), we had to perform two matches: first from `config::Language` to `languages::Language`, and then from `languages::Language.<some method>` to the actual function implementation. After #107, we only need to perform one match.

There is some boilerplate code, but it seems manageable. We could write a macro to reduce the boilerplate code into a single location. What are your thoughts on this?

**Comment by bxb100** [comment]
I prefer not to use complicated macros since they are often difficult to read and understand. However, I am open to it, if you have some good ideas, please let me know

**Comment by bxb100** [comment]
understand, my initial motivation was to eliminate `static`, if you want to keep this, I'm fine with it

**Comment by bxb100** [comment]
Hi, I’m temporarily closing this. If you need it in the future, I’ll be happy to reopen it.

**Comment by j178** [comment]
Thanks!

**Pull request closed without merging**
